### ISSUE TITLE
Getting Permission errors running Make test

### ISSUE THREAD

**Issue by lholmquist** [openshift-cloud-functions/faas-js-runtime-image#24]
Getting this error when doing `make test`

```
~/develop/openshift-cloud-functions/faas-js-runtime-image(master) » make test                                                                                        lucasholmquist@lincolnhawk2
./run-test.sh oscf/js-runtime:candidate
Testing oscf/js-runtime:candidate
Building image...
Sending build context to Docker daemon  153.6kB
Step 1/8 : FROM node:12-alpine
 ---> ef7d474eab14
Step 2/8 : EXPOSE 8080
 ---> Using cache
 ---> 84ebcbf8b92a
Step 3/8 : COPY src /home/node/src
 ---> 9f9e8d16bfe5
Step 4/8 : COPY s2i /usr/libexec/s2i
 ---> e4c2046ab91e
Step 5/8 : RUN mkdir -p /home/node/usr &&   chmod -R 777 /home/node &&   cd /home/node/src &&   npm install
 ---> Running in 35e9bc1e9f2d
npm WARN faas-js-runtime@1.0.0 No description
npm WARN faas-js-runtime@1.0.0 No repository field.
npm WARN faas-js-runtime@1.0.0 No license field.

added 17 packages from 23 contributors and audited 19 packages in 1.16s
found 0 vulnerabilities

Removing intermediate container 35e9bc1e9f2d
 ---> 3f84f0333268
Step 6/8 : ENV HOME /home/node
 ---> Running in e76842bd63b6
Removing intermediate container e76842bd63b6
 ---> 6e28b495e827
Step 7/8 : USER 1001
 ---> Running in afddc4255572
Removing intermediate container afddc4255572
 ---> f2d48bf7548a
Step 8/8 : CMD ["/home/node/src/run.sh"]
 ---> Running in 5e0f628179eb
Removing intermediate container 5e0f628179eb
 ---> d4f65e29c875
Successfully built d4f65e29c875
Successfully tagged oscf/js-runtime:candidate
Starting container for oscf/js-runtime:candidate...
docker run --rm --cidfile 157001023422934.cid -a stdout -a stderr -v /home/lucasholmquist/develop/openshift-cloud-functions/faas-js-runtime-image/test:/home/node/usr -p 8080:8080 oscf/js-runtime:candidate &
Giving it a few seconds to initialize...
Waiting for 157001023422934.cid...
+ umask 000
+ cd /home/node/usr
+ '[' -f package.json ]
+ export 'NO_UPDATE_NOTIFIER=true'
+ npm install '--only=prod'
Waiting for package-lock.json...
npm WARN checkPermissions Missing write access to /home/node/usr
npm WARN test@1.0.0 No description
npm WARN test@1.0.0 No repository field.

npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /home/node/usr
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/home/node/usr'
npm ERR!  [Error: EACCES: permission denied, access '/home/node/usr'] {
npm ERR!   stack: "Error: EACCES: permission denied, access '/home/node/usr'",
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/home/node/usr'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-10-02T09_57_19_008Z-debug.log
+ cd ../src
+ node .
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'is-number'
Require stack:
- /home/node/usr/index.js
- /home/node/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/node/usr/index.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/home/node/src/index.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/node/usr/index.js', '/home/node/src/index.js' ]
}
Waiting for package-lock.json...
Waiting for package-lock.json...
Waiting for package-lock.json...
Waiting for package-lock.json...
Waiting for package-lock.json...
Waiting for package-lock.json...
Waiting for package-lock.json...
^Cmake: *** [Makefile:15: test] Interrupt
```

My Docker version on Fedora 29
```
Client:
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:34:10 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 06:02:24 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by lholmquist** [comment]
so after doing `chmod a+w test` things worked after that,  closing
